name = input("Enter your name: ")
device = input("What device are you using? ")
operating_system = input("What is its operating system? ")
ip_address = input("Check the IP address and type it here: ")
wifi_name = input("What is your WiFi name? ")
password = input("Enter password: ")

print()
print("User Information")
print("----------------")
print("Name:", name)
print("Device:", device)
print("Operating System:", operating_system)
print("IP Address:", ip_address)
print("WiFi Name:", wifi_name)
print("Password:", password)